### ISSUE TITLE
Wouldn't it be better to add a prefix such as 'd' or 'f' or '@f' to snippet code

### ISSUE THREAD

**Issue by zswxp32** [Nash0x7E2/awesome-flutter-snippets#15]
Wouldn't it be better to add a prefix such as 'd' or 'f' or '@f' to snippet code？
This way it will be more convenient to use.

**Comment by Nash0x7E2** [comment]
Hi,
Thank you for bringing this up. @warrendodsworth suggested adding a prefix to the snippet depending on their type. Similar to Angular 8 snippets. 

I am thinking of having four prefixes:
`w-` - widgets 
`b-` -  builders. 
`c-` - classes 
`f-` - functions

Current Syntax:
```
statelessW
```

Would become:
```
w-stateless
```

Current Syntax:
```
streamBldr
```

Would Become
```
b-stream
```

cc: @georgeherby 

- Related #18

**Comment by georgeherby** [comment]
I am down with this idea :)
