### ISSUE TITLE
[Feature Request] Snippet Shortcuts begin with "f-"

### ISSUE THREAD

**Issue by warrendodsworth** [Nash0x7E2/awesome-flutter-snippets#18]
They'd be easier to find and remember if they all started with f- or fl-
Like the snippet pack for angular from Mikael Morlund
https://marketplace.visualstudio.com/items?itemName=Mikael.Angular-BeastCode

**Comment by Nash0x7E2** [comment]
Hi, 
Thank you for raising this issue. 

Since there is already an issue open on this, I am going to close this for now and we can track it from #15
