### ISSUE TITLE
How can I customize the tab spaces for snippeds?

### ISSUE THREAD

**Issue by hm1996** [Nash0x7E2/awesome-flutter-snippets#24]
Good Morning.

I used to work with 4 spaces tabs but Awesome Flutter Snippeds insert the new code with 2 spaces tab.

**Comment by Nash0x7E2** [comment]
Hi! At this time, snippets use spaces. We may change this in the future to use tabs but in either case, once a snippet is added to your code, you can selectively format the lines to match your project format. 

https://github.com/microsoft/vscode/issues/44075
