### ISSUE TITLE
[proposal] Publish "awesome-flutter-snippets" on "open-vsx"

### ISSUE THREAD

**Issue by iapicca** [Nash0x7E2/awesome-flutter-snippets#28]
Hi,
please consider helping developers on [VSCodium](https://github.com/VSCodium/vscodium) and [eclipse theia](https://theia-ide.org/) 
to have a smoother experience publishing this super-useful extension on [open-vsx](https://open-vsx.org/)
(it doesn't seem a time consuming task [link](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions))
Thank you

**Comment by Nash0x7E2** [comment]
Done: https://open-vsx.org/extension/Nash/awesome-flutter-snippets
