### ISSUE TITLE
How do one use this extension?!

### ISSUE THREAD

**Issue by yanivshaked** [Nash0x7E2/awesome-flutter-snippets#30]
Hi,

The readme is missing one little and very important note, how to use this extension.
I've downloaded and installed it on my Visual Studio code, but I have not discovered the way to use it...

Thank you,
Yaniv

**Comment by yanivshaked** [comment]
Ok, now I got it:

![image](https://user-images.githubusercontent.com/13107481/89874518-9d753a80-dbc4-11ea-9e00-67bb3f648b91.png)

Still I think the readme should have some information about it...

**Comment by Nash0x7E2** [comment]
Hi thank you for the feedback. I will add a short gif to the README to emphasize the functionality :)
