### ISSUE TITLE
Publishing to Open VSX

### ISSUE THREAD

**Issue by proninyaroslav** [Nash0x7E2/awesome-flutter-snippets#31]
Hi. It would be nice if you publish the extension on Open VSX https://open-vsx.org/. I'm using VSCodium and it uses Open VSX by default.

**Comment by Nash0x7E2** [comment]
Done: https://open-vsx.org/extension/Nash/awesome-flutter-snippets

**Comment by huang12zheng** [comment]
@Nash0x7E2 The same appeal
