### ISSUE TITLE
Generate null-safe code

### ISSUE THREAD

**Issue by jarekb123** [Nash0x7E2/awesome-flutter-snippets#34]
Currently snippets are generating legacy non null-safe code.

**Expected behavior**

Snippets are generating null-safe code.

**Comment by mohammadreza490** [comment]
Agreed this should be done!

**Comment by Nash0x7E2** [comment]
Implemented in v3: https://marketplace.visualstudio.com/items?itemName=Nash.awesome-flutter-snippets
