### ISSUE TITLE
Add Null Safety support

### ISSUE THREAD

**Issue by devmuaz** [Nash0x7E2/awesome-flutter-snippets#37]
### Description
Hi, recently I've migrated to the latest version of Flutter which is currently 2.0.3.. which also supports Null Safety.
And few little issues I found while using this snippets (which are great btw), is that it doesn't support null safety features
for example if I use the snippet **"statelessW"** it will add the following
```dart
class WidgetTest extends StatelessWidget {
  const WidgetTest({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

but, since all Null Safety features are enabled, the **Key** property should be nullable (marked with '?').. like this
```dart
class WidgetTest extends StatelessWidget {
  const WidgetTest({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

I didn't tried all the snippets if they may have the same issue, but it would be awesome if you add this features to it.

### Suggestions
- you could add an option in the settings whether to enable null safe or not.
- you could add 2 separate snippets one for null safe and one for non-null safe.
- or something else

**Comment by eladcandroid** [comment]
Hi, any news?

**Comment by devmuaz** [comment]
@eladcandroid unfortunately, still get no response about this issue.

**Comment by eladcandroid** [comment]
@Nash0x7E2

**Comment by evaqum** [comment]
The code for snippets is already updated to support null-safety, but for some reason author didn't update the extension

**Comment by Nash0x7E2** [comment]
Migrating this now, sorry for the delay everyone 🙈

**Comment by Nash0x7E2** [comment]
Implemented in v3: https://marketplace.visualstudio.com/items?itemName=Nash.awesome-flutter-snippets
