### ISSUE TITLE
update snippets to flutter 3

### ISSUE THREAD

**Issue by ghost** [Nash0x7E2/awesome-flutter-snippets#58]
currently the snippets don't seem to leverage flutter 3 features

e.g.:`statelessW` 

- expected result

```dart
class name extends StatelessWidget {
  const name({super.key});

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

- actual result

```dart
class name extends StatelessWidget {
  const name({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

**Comment by deandreamatias** [comment]
Implement compatibility with different major Flutter versions will be nice (related with #41) . Maybe a property config

**Comment by Nash0x7E2** [comment]
Plugin is now updated for v3 => https://marketplace.visualstudio.com/items?itemName=Nash.awesome-flutter-snippets
