### ISSUE TITLE
Stateful and Statless Widget

### ISSUE THREAD

**Issue by adriank** [Nash0x7E2/awesome-flutter-snippets#6]
Hi,

You removed Stateful and Statless Widget from this library because Dart Code has them. How to access them? I don't see anything similar in their documentation.

Thanks,
Adrian

**Comment by ch3ckmat3** [comment]
Yes, same here. please bring these back!!!

**Comment by ch3ckmat3** [comment]
like now!

**Comment by YeFei572** [comment]
+1,
I hava install the older version. but it's fell bad.
![image](https://user-images.githubusercontent.com/26360338/56297022-2495d800-6162-11e9-9275-85c0e2c199c6.png)

**Comment by Nash0x7E2** [comment]
Hello, 
I removed `Stateful`/`Stateless` widget from the extension since they are included with the official DartCode plugin and would sometimes conflict with one another while typing. I've noticed a few times while coding that intelisense would show `Stateful` templates from both Awesome Flutter Snippets and Dart code making it easy to accidentally chose the wrong snippet. 

That said, I will add both snippets back to the plugin and release an update later today since a lot of people have requested that they are re-added. 

Sorry for the inconvenience, 
Nash

**Comment by adriank** [comment]
@Nash0x7E2 how did you get these snippets from the official dart-code extension? They are not there. Maybe you have them from another extension?

**Comment by Nash0x7E2** [comment]
They usually come up whenever I start typing "state..." or whenever I hit `Ctrl + Space`. 

I have no other Flutter related extensions installed so I'm positive they're coming from DartCode. The three snippets I see the most are `Stateless Widgets`, `Stateful Widget` and `Stateful widget with animation controller`.

**Comment by Nash0x7E2** [comment]
I just checked the source and yes, it is indeed coming from DartCode https://github.com/Dart-Code/Dart-Code/blob/master/snippets/flutter.json

**Comment by adriank** [comment]
I see the same snippets, but they're gone if I move to the new version of your extension. Maybe VSC assigned shortcuts to your extension and they're not available from Dart-code?

**Comment by Nash0x7E2** [comment]
That's really strange but I'll have the snippets added back to the extension this evening.

**Comment by ch3ckmat3** [comment]
@Nash0x7E2 Thanks man!
Dart-Code snippet shortcuts are not intuitive, I didn't event notice until I read your release notes... then I had to find them to see event if they existed, and are even functioning as expected.

Do notify here as you post update. 

👍🙌

**Comment by Nash0x7E2** [comment]
@adriank @ch3ckmat3 The fix is live on the VsCode marketplace.

**Comment by fibbers** [comment]
Thanks for bringing the snippets back! 👍 

For anyone else not seeing the Flutter snippets from Dart-Code (I also didn't know about them and didn't see them):
That might be related to https://github.com/Dart-Code/Dart-Code/issues/1625 and should be fixed in v2.26.0 reading the milestone comments.
