### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by gkpiccoli** [Nash0x7E2/awesome-flutter-snippets#62]
Hi, I tried to install this plugin but it is not showing up in the plugin store. In the marketplace section the 404 error is displayed. What's happening? Thanks for sharing knowledge.

**Comment by Nash0x7E2** [comment]
Hey! I'm sorry for the inconvenience caused here. 

While updating the plugin for V3 support, the organization was accidentally deleted.

You can download the new version directly from the Marketplace here: https://marketplace.visualstudio.com/items?itemName=Nash.awesome-flutter-snippets

More info: https://www.linkedin.com/feed/update/urn:li:activity:6961025981104984064/

**Comment by gkpiccoli** [comment]
Thank you! Your job is awesome!!!
