### ISSUE TITLE
I wanted to install this plug in the extensions  marketplace but it doesn't exist. Please help !

### ISSUE THREAD

**Issue by MohammadRaficHalwani** [Nash0x7E2/awesome-flutter-snippets#63]

**Comment by marembu** [comment]
Same here!

**Comment by Nash0x7E2** [comment]
Hey! I'm sorry for the inconvenience caused here. 

While updating the plugin for V3 support, the organization was accidentally deleted.

You can download the new version directly from the Marketplace here: https://marketplace.visualstudio.com/items?itemName=Nash.awesome-flutter-snippets

More info: https://www.linkedin.com/feed/update/urn:li:activity:6961025981104984064/

**Comment by marembu** [comment]
Thanks @Nash0x7E2
