### ISSUE TITLE
Missing @override annotation in statefulW

### ISSUE THREAD

**Issue by nbros** [Nash0x7E2/awesome-flutter-snippets#8]
When I convert a stateless widget to a stateful Widget, an ```@override``` annotation is added on ```createState```:
![image](https://user-images.githubusercontent.com/141089/63332286-90b66180-c337-11e9-8f40-d6ee6424c427.png)

![image](https://user-images.githubusercontent.com/141089/63332341-b80d2e80-c337-11e9-897b-02a0950df304.png)

But when creating a stateful Widget using the "statefulW" template no ```@override``` annotation is added on ```createState```:
![image](https://user-images.githubusercontent.com/141089/63332688-54cfcc00-c338-11e9-8bc2-d256ba80bada.png)

![image](https://user-images.githubusercontent.com/141089/63332743-687b3280-c338-11e9-970a-eec266991387.png)

For consistency, the @override annotation should also be added by the snippet since Dart Code adds it.

**Comment by jeroen-meijer** [comment]
This is not part of the Awesome Flutter Snippets extension, but rather [the Flutter extension written by Dan Tup](https://dartcode.org/). If this issue is still here, please report an issue on his repo.

**Comment by Nash0x7E2** [comment]
Hi, thank you for taking the time to open an issue. As @jeroen-meijer pointed out, `Convert to SatefulWidget` is coming from the official Flutter plugin, not AFS.
